### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by mplpl** [comment]
@polluks Thank you very much for committing this translation. 
I see you got the ct file from conversion from rar.lng using the attached script. The extension of this file suggests that it was made for WinRAR translation and since WinRAR is a commercial program, I have to as who own the copyrights to that lng file?

Thanks in advance for answering.

**Comment by polluks** [comment]
I see, you may ask the author http://leimer.name/kontakt/index.html.

**Comment by mplpl** [comment]
I'll do that. Thanks you.

**Comment by mplpl** [comment]
Good news. win.rar GmbH granted permission for using the German translation to this open-source unrar port.
I'm about to merge this pull request. Letter on, I will also regenerate the ct file from the up-to-date German translation file.

**Review by mplpl — APPROVED** [review]

**Pull request merged**
